front_scan_filter:
  ros__parameters:
    filter1:
      name: angle
      type: laser_filters/LaserScanAngularBoundsFilterInPlace
      params:
        lower_angle: -1.5707963   # -90
        upper_angle: 1.5707963   # +90
    filter2:
      name: box
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: Base_footprint
        min_x: -0.30        
        max_x:  0.35      
        min_y: -0.32       
        max_y:  0.32       
        min_z: -0.10       
        max_z:  0.30      
        invert: false    